nelmio_api_doc:
    documentation:
        info:
            title: Application
            description: Api REST
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
        host_patterns:
            - ^api\.
